// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFdyRK2P-Ci08Ye5gfPPwzuyYmYmilPw',
    appId: '1:635768197518:web:b3d6111369f3c97dc914df',
    messagingSenderId: '635768197518',
    projectId: 'homelypath',
    authDomain: 'homelypath.firebaseapp.com',
    storageBucket: 'homelypath.firebasestorage.app',
    measurementId: 'G-77V33HPBJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZYW8Uz7fDj_Is4GzhcWNqQfteDKIlppI',
    appId: '1:635768197518:android:ac6e7b49e907a3e8c914df',
    messagingSenderId: '635768197518',
    projectId: 'homelypath',
    storageBucket: 'homelypath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPvK-eqhRabZvGS-fiEKoDwbnQJIMrMs',
    appId: '1:635768197518:ios:fac344f4e144aaf0c914df',
    messagingSenderId: '635768197518',
    projectId: 'homelypath',
    storageBucket: 'homelypath.firebasestorage.app',
    iosBundleId: 'com.aw.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfPvK-eqhRabZvGS-fiEKoDwbnQJIMrMs',
    appId: '1:635768197518:ios:fac344f4e144aaf0c914df',
    messagingSenderId: '635768197518',
    projectId: 'homelypath',
    storageBucket: 'homelypath.firebasestorage.app',
    iosBundleId: 'com.aw.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFdyRK2P-Ci08Ye5gfPPwzuyYmYmilPw',
    appId: '1:635768197518:web:a16ba62ae60cc6dac914df',
    messagingSenderId: '635768197518',
    projectId: 'homelypath',
    authDomain: 'homelypath.firebaseapp.com',
    storageBucket: 'homelypath.firebasestorage.app',
    measurementId: 'G-7HY30W05KV',
  );
}
